### ISSUE TITLE
docker-registry-sync tag fails if images already exist on local docker client

### ISSUE THREAD

**Issue by JayKayy** [rhtconsulting/rhc-ose#105]
It may be designed this way intentionally and just the documentation is not there.

Problem:

It should be known or fixed that the `awk` for setting the image_id variable will set image_id equal to all the image id's that docker has locally(outside of this script). The current version of the script works with an absolute clean docker storage i.e. no images have been pulled by it before.
Line:
https://github.com/rhtconsulting/rhc-ose/blob/openshift-enterprise-3/docker-registry-sync#L15

When not clean storage then the docker tag attempt errors out looking like this

`docker tag 3fc68076e184`
`<existing image ID>`
`...`
`<existing image ID> <target registry>`

Giving the error that docker tag requires 2 arguments.

**Comment by etsauer** [comment]
@JayKayy you think we could convert that thing to ansible? make it more idempotent?

**Comment by JayKayy** [comment]
@etsauer yea and it really shouldnt be that hard at all. Ill add this to my queue
