### ISSUE TITLE
'openstack-create' ansible role should allow for creation of custom security groups

### ISSUE THREAD

**Issue by etsauer** [rhtconsulting/rhc-ose#106]
@sabre1041 does the nova_compute module accomodate this?

**Comment by sabre1041** [comment]
What do you mean by this?

`nova_compute` allows for custom security groups to be passed in and `security_groups` is a parameter that should be passed to the `openstack-create` role

https://github.com/rhtconsulting/rhc-ose/blob/openshift-enterprise-3/rhc-ose-ansible/ose-provision.yml#L24

**Comment by etsauer** [comment]
Right, that's just the name of the security groups. What I mean is does nova_compute allow us to define security groups that don't already exist, so that, say we wouldn't have to worry about pre-creating them in a new tenant?

**Comment by vvaldez** [comment]
Added this feature in PR #135
