### ISSUE TITLE
jekyll-asciidoc-docker instructions use incorrect path

### ISSUE THREAD

**Issue by lawnjarae** [rhtconsulting/rhc-ose#120]
The first line in the **Running** section contains the line:
$ ./docker/openstack-docker-client/run.sh --help

This points to the incorrect docker image and should be changed to:
$ ./docker/jekyll-asciidoc/run.sh --help

**Comment by etsauer** [comment]
@lawnjarae check now. PR just merged with fix.

**Comment by sabre1041** [comment]
This has been resolved. Closing
