### ISSUE TITLE
Implement dynamic disk partitioning to avoid a fixed 25GB per instance.

### ISSUE THREAD

**Issue by oybed** [rhtconsulting/rhc-ose#13]
The provisioning tools should support creating any sized disk volume with the corresponding OSE/Docker partitions. Right now this is fixed at 25GB total - with 20GB Docker and 2GB OSE (with ~3GB to spare). The change should allow for any reasonably sized volume (downwards of ~5GB minimum)

**Comment by etsauer** [comment]
@oybed we're done with this right?

**Comment by oybed** [comment]
@etsauer yes, done - will close out.
