### ISSUE TITLE
openstack-docker-client container cannot resolve os1 endpoint

### ISSUE THREAD

**Issue by JaredBurck** [rhtconsulting/rhc-ose#15]
While trying to run the provision.sh script (within the container), the nova client would error out, for example:

```
# ./provision.sh --action boot --instance-name jburck-master00 --key jburck --image-name os3-base --security-groups ${SECURITY_GROUP_CICD} --num-instances 1 --debug
Tail Logfile for More Info: /root/openstack_provision.log
ERROR (ConnectionError): ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```

Tried simply connecting with nova client and it also returned an error:

```
# nova image-list
ERROR (ConnectionError): ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```

Work around from Andy Block, was to add os1 endpoint to /etc/hosts file. Could possibly add some logic to somehow grab that information.

**Comment by sabre1041** [comment]
This issue may be limited to only boot2docker/osx issues

@etsauer were you able to use the docker container option without needing to modify the `/etc/hosts` file?

**Comment by etsauer** [comment]
@sabre1041 yes I was. I can test again today.

**Comment by etsauer** [comment]
@sabre1041 @JaredBurck have we gotten this resolved? Is it an OS compatibility issue?

**Comment by sabre1041** [comment]
@etsauer looks to be an issue with OSX/boot2docker. We can proactively prompt the user of this issue and provide them the necessary commands to execute in the container if it is detected they are running boot2docker.

thoughts?

**Comment by etsauer** [comment]
@sabre1041 I think just add a known issues section to the README. Also, I think it's our civic duty to open an issue with boot2docker: https://github.com/boot2docker/boot2docker

**Comment by etsauer** [comment]
@JaredBurck could you try all of this using the new, "Docker Toolbox" rather than Boot2Docker? if that works better we'll probably just want to avoid using boot2docker anymore.

https://docs.docker.com/mac/step_one/

**Comment by oybed** [comment]
@JaredBurck @sabre1041 @etsauer this looks similar to another issue I helped some guys with the other day. Basically, when using Mac OS and VPN, the DNS servers doesn't get updated properly within the OS. Browsers know to pick up the correct DNS servers provided by the VPN, but the CLI/terminal don't. Since this is docker based, and CLI, it leads me to believe it's the same issue. One "workaround" to try is to update /etc/resolv.conf on your Mac to point to the DNS servers provided by the VPN and that should fix it (may have to re-deploy the docker image to pick up the correct servers).  Another option to try would be something like

```
DOCKER_OPTS="--dns=<private-dns-server-ip> --dns=<public-dns-server-ip>"
```

**Comment by sabre1041** [comment]
@JaredBurck @etsauer @oybed 

Updated my boot2docker image and client and was able to resolve endpoint without needing to make any manual configuration changes

@JaredBurck would you be able to update and retest?

**Comment by JaredBurck** [comment]
I have updated my OS X environment to the latest docker version 1.8.3 using the docker toolbox.  I still have the same issue where I can cannot resolve the endpoint without adding it to /etc/hosts file.

@oybed thanks, I will try your suggested workarounds and report back.

My Windows 7 environment is having issues getting docker working (cannot connect to docker vm).  Once I resolve the issues I will test the container and see if this issue exists on this platform.

**Comment by sabre1041** [comment]
Closing issue as it does not appear to be affecting the majority of users. Will reopen if necessary
