### ISSUE TITLE
repo in openstack-docker-client image has been EOL'd (rdo-release-juno.rpm)

### ISSUE THREAD

**Issue by JayKayy** [rhtconsulting/rhc-ose#158]
When running `rhc-ose/docker/openstack-docker-client/run.sh` I get an error in the docker build fo the following repo: https://repos.fedorapeople.org/repos/openstack/openstack-juno/rdo-release-juno.rpm

This error prevents the nova client from installing into the docker image and prevents provisionsing.

**Comment by etsauer** [comment]
@JayKayy ok, let me try to rebuild my image this morning

**Comment by etsauer** [comment]
@JayKayy I do not have this issue. I think that has to do with your local yum/dnf config

**Comment by etsauer** [comment]
Oh, nvm, i did get it...
