### ISSUE TITLE
Hostnames reset after reboot

### ISSUE THREAD

**Issue by JayKayy** [rhtconsulting/rhc-ose#181]
after a `reboot` the host comes back up without the short hostname set. e.g: 

`[root@node3.example.com ~]# reboot`
boots back up to:
`[root@node3-casl-jkwiatko-dmlmz4j9 ~]#`

**Comment by oybed** [comment]
Example on how it can be solved:
https://github.com/rhtconsulting/rhc-ose/blob/openshift-enterprise-3/provisioning/osc-dns-config#L225-L226

**Comment by oybed** [comment]
I'll be working this together with #183
