### ISSUE TITLE
Instance names in openstack-create role should be of the form <instance-name>.<env_id>

### ISSUE THREAD

**Issue by etsauer** [rhtconsulting/rhc-ose#208]
This will result in much cleaner fqdns.

For example, today I get an fqdn for an instance that looks like:
`casl-esauer-1467940863-node4.example.com`

I would like that to be:
`node4.casl-esauer-1467940863.example.com`

@vvaldez @oybed @sabre1041

**Comment by oybed** [comment]
@etsauer - this is in many ways taking it back to what we used to have (and the "struggle" with custom host names. We may benefit from Ansible 2.x, however). Let's schedule a quick meeting to discuss when I'm back from vacation.

**Comment by etsauer** [comment]
@oybed sounds good. 

Additionally, right now if I specify an ENV_ID, I still get a generated (date) string tacked on. That shouldn't happen, or at least we need to be able to avoid that for permanent environments.

**Comment by vvaldez** [comment]
This goes back to PR #149 which was to group clusters together on the CLI and UI when multiple clusters are deployed in the same project. This proposed change would revert that so you would have all "node4.*" grouped together from different clusters and so on. We have to decide what is more important or provide a way to customize it.
