### ISSUE TITLE
DNS instance should not provision volume

### ISSUE THREAD

**Issue by oybed** [rhtconsulting/rhc-ose#225]
With the latest ansible based tools, the DNS instance is also getting assigned an additional volume for storage. This isn't necessary and is wasting resources. Should be at least made optional and disabled by default.

**Comment by sabre1041** [comment]
@oybed the `openstack-create` node has logic to only create volumes when sizes are specified

https://github.com/rhtconsulting/rhc-ose/blob/openshift-enterprise-3/rhc-ose-ansible/roles/openstack-create/tasks/main.yml#L90-L97

Could be reuse of previously defined variables?

**Comment by oybed** [comment]
@sabre1041 agreed. This issue was opened just to track the default behavior that seemed to have changed in the later versions of the tools - i.e.: it used to _not_ assign a volume to the dns instance by default.

**Comment by sabre1041** [comment]
@oybed what version of ansible are you running? My latest run 2 weeks ago with ansible `2.1.0.0` did not attach a volume

**Comment by oybed** [comment]
@sabre1041 NVM - appears I need to learn how to count. It was an oversight from my side. :-) Closing it out.
