### ISSUE TITLE
Update SSH Mount point

### ISSUE THREAD

**Issue by sabre1041** [rhtconsulting/rhc-ose#24]
Due to issues found when directly mounting, revert the changes to mounting the SSH directory within the container at `/mnt/ssh` and copy over the content to the `~/.ssh` directory.

**Comment by etsauer** [comment]
@sabre1041 opened https://github.com/rhtconsulting/rhc-ose/pull/25 for this

**Comment by sabre1041** [comment]
Fixed by #25
