### ISSUE TITLE
osc-provision usage text incorrect

### ISSUE THREAD

**Issue by JayKayy** [rhtconsulting/rhc-ose#36]
the --config-file=<path> is incorrect and should read --config=<path>

Also it should be noted that it must be an absolute path. eg when i tried ~/devel/os1.config it couldnt find the file. but /home/jkwiatko/devel/os1.config fixed the issue.

**Comment by etsauer** [comment]
@JayKayy there is a PR open for this: https://github.com/rhtconsulting/rhc-ose/pull/38

Will you please review?
