### ISSUE TITLE
Provisioning instances fail due to timeout

### ISSUE THREAD

**Issue by JaredBurck** [rhtconsulting/rhc-ose#55]
When trying to provision OS1 environments the scripts, provisioning can fail due to reaching the 120 second timeout while waiting for the ssh service to be ready.  

From provision.sh boot_servers() function

```
# need to wait until ssh service comes up on instance
wait_for_ssh ${instance_ip#*,} 120
```

Suggest increasing this value to 150, which has worked much better for me.

**Comment by oybed** [comment]
Issue #34 will take care of this problem- PR in the works

**Comment by JaredBurck** [comment]
@oybed thanks! Closing issue.
