### ISSUE TITLE
Using the --openshift-domain CLI option doesn't work

### ISSUE THREAD

**Issue by oybed** [rhtconsulting/rhc-ose#6]
Attempting to provision a new environment with a custom domain does not seem to work anymore. 

For example, running:

```
./rhc-ose/provisioning/osc-provision --num-nodes=3 --openshift-domain=obedin.rhc-ose.labs.redhat.com --key=obedin-ose3-pub-key
```

should install an environment using "obedin.rhc-ose.labs.redhat.com" as the domain, but instead it installs it with "ose.example.com"

**Comment by etsauer** [comment]
@oybed yeah, i think that since we can now override all of these by passing the --config=file option, i'm going to remove the following options:

```
  --openshift-domain=<domain>   : Base domain name for your OpenShift environment (default: ose.example.com)
  --cloudapp-subdomain=<domain> : Wildcard domain for your applications (default: *.apps)
```

**Comment by etsauer** [comment]
@oybed https://github.com/rhtconsulting/rhc-ose/pull/7 takes care of this

**Comment by etsauer** [comment]
@oybed can we close this issue?
