### ISSUE TITLE
Etcd in standalone mode does not write to /var/lib/openshift

### ISSUE THREAD

**Issue by etsauer** [rhtconsulting/rhc-ose#87]
We configure 'openshift' storage assuming an embedded etcd writing to `/var/lib/openshift`, however our ansible inventory template provisions etcd in standalone, which stores data in `/var/lib/etcd`. We should change the `setup_openshift_storage` method to use `/var/lib/etcd`

**Comment by oybed** [comment]
This was fixed by PR #88
